"""Reproducible generator for bundled raster fixtures.

Implements Steps 3 and 4 of ``docs/plans/archive/08-raster-action-plan.md``: each
fixture is built from a deterministic numpy array with explicit metadata
(CRS, transform, dtype, nodata, band names, compression) so the committed
GeoTIFFs can be regenerated byte-stably instead of being opaque blobs.

Usage::

    python scripts/generate_raster_fixtures.py            # write all fixtures
    python scripts/generate_raster_fixtures.py --check    # verify up to date

The generator only writes the ``.tif`` primary files. Case metadata
(``case.yaml`` / ``notes.md``) is authored alongside and indexed via
``scripts/build_case_index.py``.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
import rasterio
from rasterio.enums import Resampling
from rasterio.transform import from_origin

REPO_ROOT = Path(__file__).resolve().parents[1]
RASTER_ROOT = REPO_ROOT / "src" / "geocase" / "data" / "core" / "raster"

# A small UTM-like transform shared by the synthetic scenes (10 m pixels).
_TRANSFORM = from_origin(500000.0, 4500000.0, 10.0, 10.0)
_CRS = "EPSG:32633"
_SIZE = 16


@dataclass
class RasterSpec:
    """Declarative description of a synthetic raster fixture."""

    case_id: str
    primary: str
    bands: list[np.ndarray]
    dtype: str
    nodata: float | int | None = None
    band_names: list[str] = field(default_factory=list)
    compression: str | None = None
    # CRS / transform overrides for geography-specific scenes.
    crs: str = _CRS
    transform: Any | None = None
    # COG-style / overview controls.
    tiled: bool = False
    block_size: int = 16
    overviews: list[int] = field(default_factory=list)
    external_overviews: bool = False
    # Per-dataset band scale factor (e.g. scaled int16 reflectance).
    scale_factor: float | None = None
    # Single-band categorical colormap: {value: (r, g, b, a)}.
    colormap: dict[int, tuple[int, int, int, int]] | None = None

    def array(self) -> np.ndarray:
        return np.stack(self.bands).astype(self.dtype)

    def resolved_transform(self) -> Any:
        return self.transform if self.transform is not None else _TRANSFORM


def _ramp(seed: int) -> np.ndarray:
    """Deterministic 16x16 gradient array, offset by *seed*."""
    rows = np.arange(_SIZE).reshape(-1, 1)
    cols = np.arange(_SIZE).reshape(1, -1)
    return (rows + cols + seed) % 256


def _specs() -> list[RasterSpec]:
    """Build the Priority 1 EO fixture specifications."""
    # optical_rgb_small — 3-band uint8 RGB.
    rgb = [
        _ramp(0).astype("uint8"),
        _ramp(64).astype("uint8"),
        _ramp(128).astype("uint8"),
    ]

    # multispectral_s2_like_small — 4-band uint16 (B, G, R, NIR) reflectance.
    ms = [(_ramp(s) * 40).astype("uint16") for s in (10, 20, 30, 40)]

    # water_mask_small — single-band uint8 binary mask (0/1) with nodata 255.
    mask = np.zeros((_SIZE, _SIZE), dtype="uint8")
    mask[4:12, 4:12] = 1
    mask[0, 0] = 255  # one nodata pixel

    # dem_small — single-band float32 elevation with a NaN nodata pixel.
    dem = (_ramp(0).astype("float32") * 3.5) + 100.0
    dem[15, 15] = np.nan

    # ndvi_small — single-band float32 in [-1, 1].
    ndvi = ((_ramp(0).astype("float32") / 255.0) * 2.0) - 1.0

    return [
        RasterSpec(
            case_id="optical_rgb_small",
            primary="optical_rgb_small.tif",
            bands=rgb,
            dtype="uint8",
            band_names=["red", "green", "blue"],
            compression="deflate",
        ),
        RasterSpec(
            case_id="multispectral_s2_like_small",
            primary="multispectral_s2_like_small.tif",
            bands=ms,
            dtype="uint16",
            nodata=0,
            band_names=["blue", "green", "red", "nir"],
            compression="deflate",
        ),
        RasterSpec(
            case_id="water_mask_small",
            primary="water_mask_small.tif",
            bands=[mask],
            dtype="uint8",
            nodata=255,
            band_names=["water"],
            compression="deflate",
        ),
        RasterSpec(
            case_id="dem_small",
            primary="dem_small.tif",
            bands=[dem],
            dtype="float32",
            nodata=float("nan"),
            band_names=["elevation"],
            compression="deflate",
        ),
        RasterSpec(
            case_id="ndvi_small",
            primary="ndvi_small.tif",
            bands=[ndvi],
            dtype="float32",
            band_names=["ndvi"],
            compression="deflate",
        ),
        *_priority_2_4_specs(),
    ]


def _priority_2_4_specs() -> list[RasterSpec]:
    """Build the Priority 2–4 raster families (Step 9 of the action plan)."""
    from rasterio.transform import from_origin as _origin

    # -- Priority 2: COG / overviews / compression ------------------------
    # COG scenes are 64x64 so a 16px internal tiling actually registers
    # (a 16x16 scene fits in a single block and GDAL stores it untiled).
    def _ramp64(seed: int) -> np.ndarray:
        rows = np.arange(64).reshape(-1, 1)
        cols = np.arange(64).reshape(1, -1)
        return (rows + cols + seed) % 256

    cog_single = [(_ramp64(5) * 20).astype("uint16")]
    cog_ms = [(_ramp64(s) * 30).astype("uint16") for s in (10, 20, 30, 40)]
    ovr_band = [(_ramp64(7)).astype("uint8")]

    # -- Priority 3: SAR + geography --------------------------------------
    # SAR amplitude-like float32 scenes.
    sar_vv = [(_ramp(3).astype("float32") / 255.0)]
    sar_dual = [
        (_ramp(3).astype("float32") / 255.0),
        (_ramp(9).astype("float32") / 255.0),
    ]
    optical = [
        _ramp(0).astype("uint8"),
        _ramp(64).astype("uint8"),
        _ramp(128).astype("uint8"),
    ]
    # Geographic (lon/lat) transforms with ~0.01 deg pixels.
    polar_tx = _origin(-2_000_000.0, 2_000_000.0, 10.0, 10.0)  # EPSG:3995 metres
    dateline_tx = _origin(179.9, 1.0, 0.02, 0.02)  # straddles +180 lon
    equator_tx = _origin(10.0, 0.16, 0.01, 0.01)  # centred on the equator

    # -- Priority 4: mixed resolution / NaN DEM / scaled NDVI / landcover --
    mixed = [
        (_ramp(10) * 30).astype("uint16"),
        (_ramp(20) * 30).astype("uint16"),
        (_ramp(30) * 30).astype("uint16"),
    ]
    dem_nan = (_ramp(0).astype("float32") * 4.0) + 50.0
    dem_nan[0, 0] = np.nan
    dem_nan[15, 15] = np.nan
    # Scaled int16 NDVI: physical NDVI in [-1, 1] stored as int16 * 1e-4.
    ndvi_phys = ((_ramp(0).astype("float32") / 255.0) * 2.0) - 1.0
    ndvi_int16 = np.round(ndvi_phys / 1e-4).astype("int16")
    # Categorical land cover: 0=nodata, 1=water, 2=veg, 3=urban.
    landcover = np.zeros((_SIZE, _SIZE), dtype="uint8")
    landcover[:8, :8] = 1
    landcover[:8, 8:] = 2
    landcover[8:, :8] = 3
    landcover[8:, 8:] = 2
    landcover_cmap = {
        0: (0, 0, 0, 0),
        1: (0, 0, 255, 255),
        2: (0, 200, 0, 255),
        3: (128, 128, 128, 255),
    }

    return [
        RasterSpec(
            case_id="cog_singleband_small",
            primary="cog_singleband_small.tif",
            bands=cog_single,
            dtype="uint16",
            band_names=["intensity"],
            compression="deflate",
            tiled=True,
            overviews=[2],
        ),
        RasterSpec(
            case_id="cog_multispectral_small",
            primary="cog_multispectral_small.tif",
            bands=cog_ms,
            dtype="uint16",
            nodata=0,
            band_names=["blue", "green", "red", "nir"],
            compression="deflate",
            tiled=True,
            overviews=[2],
        ),
        RasterSpec(
            case_id="geotiff_external_overviews_small",
            primary="geotiff_external_overviews_small.tif",
            bands=ovr_band,
            dtype="uint8",
            band_names=["gray"],
            compression="deflate",
            overviews=[2],
            external_overviews=True,
        ),
        RasterSpec(
            case_id="sar_vv_small",
            primary="sar_vv_small.tif",
            bands=sar_vv,
            dtype="float32",
            band_names=["VV"],
            compression="deflate",
        ),
        RasterSpec(
            case_id="sar_dualpol_small",
            primary="sar_dualpol_small.tif",
            bands=sar_dual,
            dtype="float32",
            band_names=["VV", "VH"],
            compression="deflate",
        ),
        RasterSpec(
            case_id="optical_polar_small",
            primary="optical_polar_small.tif",
            bands=optical,
            dtype="uint8",
            band_names=["red", "green", "blue"],
            compression="deflate",
            crs="EPSG:3995",
            transform=polar_tx,
        ),
        RasterSpec(
            case_id="optical_dateline_small",
            primary="optical_dateline_small.tif",
            bands=optical,
            dtype="uint8",
            band_names=["red", "green", "blue"],
            compression="deflate",
            crs="EPSG:4326",
            transform=dateline_tx,
        ),
        RasterSpec(
            case_id="optical_equator_small",
            primary="optical_equator_small.tif",
            bands=optical,
            dtype="uint8",
            band_names=["red", "green", "blue"],
            compression="deflate",
            crs="EPSG:4326",
            transform=equator_tx,
        ),
        RasterSpec(
            case_id="multispectral_mixed_resolution_small",
            primary="multispectral_mixed_resolution_small.tif",
            bands=mixed,
            dtype="uint16",
            nodata=0,
            band_names=["red_10m", "nir_10m", "swir_20m"],
            compression="deflate",
        ),
        RasterSpec(
            case_id="dem_nan_nodata_small",
            primary="dem_nan_nodata_small.tif",
            bands=[dem_nan],
            dtype="float32",
            nodata=float("nan"),
            band_names=["elevation"],
            compression="deflate",
        ),
        RasterSpec(
            case_id="ndvi_scaled_int16_small",
            primary="ndvi_scaled_int16_small.tif",
            bands=[ndvi_int16],
            dtype="int16",
            nodata=-32768,
            band_names=["ndvi"],
            compression="deflate",
            scale_factor=1e-4,
        ),
        RasterSpec(
            case_id="landcover_small",
            primary="landcover_small.tif",
            bands=[landcover],
            dtype="uint8",
            nodata=0,
            band_names=["landcover"],
            compression="deflate",
            colormap=landcover_cmap,
        ),
    ]


def _write_raster(spec: RasterSpec, dest: Path) -> None:
    """Write *spec* to *dest* with explicit, deterministic profile."""
    array = spec.array()
    height, width = array.shape[1], array.shape[2]
    profile = {
        "driver": "GTiff",
        "height": height,
        "width": width,
        "count": array.shape[0],
        "dtype": spec.dtype,
        "crs": spec.crs,
        "transform": spec.resolved_transform(),
    }
    if spec.nodata is not None:
        profile["nodata"] = spec.nodata
    if spec.compression is not None:
        profile["compress"] = spec.compression
    if spec.tiled:
        profile["tiled"] = True
        profile["blockxsize"] = spec.block_size
        profile["blockysize"] = spec.block_size

    # Stale external overviews would otherwise be read back transparently.
    sidecar = dest.with_suffix(dest.suffix + ".ovr")
    if sidecar.exists():
        sidecar.unlink()

    dest.parent.mkdir(parents=True, exist_ok=True)
    with rasterio.open(dest, "w", **profile) as dst:
        dst.write(array)
        if spec.band_names:
            for idx, name in enumerate(spec.band_names, start=1):
                dst.set_band_description(idx, name)
        if spec.scale_factor is not None:
            dst.scales = (spec.scale_factor,) * array.shape[0]
        if spec.colormap is not None:
            dst.write_colormap(1, spec.colormap)
        # Internal overviews (COG-style) are written inside the same file.
        if spec.overviews and not spec.external_overviews:
            dst.build_overviews(spec.overviews, Resampling.nearest)
            dst.update_tags(ns="rio_overview", resampling="nearest")

    # External overviews are built in a second pass on the read-only dataset,
    # which makes GDAL emit a sibling ``.ovr`` sidecar instead of embedding.
    if spec.overviews and spec.external_overviews:
        from osgeo import gdal

        gdal.UseExceptions()
        ds = gdal.Open(str(dest), gdal.GA_ReadOnly)
        try:
            ds.BuildOverviews("NEAREST", spec.overviews)
        finally:
            ds = None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate bundled raster fixtures.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any fixture would change instead of writing it.",
    )
    parser.add_argument(
        "--raster-root",
        type=Path,
        default=RASTER_ROOT,
        help="Root directory for raster case folders.",
    )
    return parser.parse_args()


def main() -> int:
    """CLI entrypoint."""
    args = parse_args()
    specs = _specs()

    if args.check:
        import tempfile

        stale: list[str] = []
        for spec in specs:
            dest = args.raster_root / spec.case_id / spec.primary
            if not dest.exists():
                stale.append(spec.case_id)
                continue
            with tempfile.TemporaryDirectory() as tmp:
                candidate = Path(tmp) / spec.primary
                _write_raster(spec, candidate)
                if candidate.read_bytes() != dest.read_bytes():
                    stale.append(spec.case_id)
        if stale:
            print(f"Raster fixtures out of date: {', '.join(stale)}")
            return 1
        print("All raster fixtures up to date")
        return 0

    for spec in specs:
        dest = args.raster_root / spec.case_id / spec.primary
        _write_raster(spec, dest)
        print(f"Wrote {dest.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
