"""Reproducible generator for bundled raster fixtures.

Implements Steps 3 and 4 of ``docs/plans/08-raster-action-plan.md``: each
fixture is built from a deterministic numpy array with explicit metadata
(CRS, transform, dtype, nodata, band names, compression) so the committed
GeoTIFFs can be regenerated byte-stably instead of being opaque blobs.

Usage::

    python scripts/generate_raster_fixtures.py            # write all fixtures
    python scripts/generate_raster_fixtures.py --check    # verify up to date

The generator only writes the ``.tif`` primary files. Case metadata
(``case.yaml`` / ``notes.md``) is authored alongside and indexed via
``scripts/build_case_index.py``.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import rasterio
from rasterio.transform import from_origin

REPO_ROOT = Path(__file__).resolve().parents[1]
RASTER_ROOT = REPO_ROOT / "src" / "geocase" / "data" / "core" / "raster"

# A small UTM-like transform shared by the synthetic scenes (10 m pixels).
_TRANSFORM = from_origin(500000.0, 4500000.0, 10.0, 10.0)
_CRS = "EPSG:32633"
_SIZE = 16


@dataclass
class RasterSpec:
    """Declarative description of a synthetic raster fixture."""

    case_id: str
    primary: str
    bands: list[np.ndarray]
    dtype: str
    nodata: float | int | None = None
    band_names: list[str] = field(default_factory=list)
    compression: str | None = None

    def array(self) -> np.ndarray:
        return np.stack(self.bands).astype(self.dtype)


def _ramp(seed: int) -> np.ndarray:
    """Deterministic 16x16 gradient array, offset by *seed*."""
    rows = np.arange(_SIZE).reshape(-1, 1)
    cols = np.arange(_SIZE).reshape(1, -1)
    return (rows + cols + seed) % 256


def _specs() -> list[RasterSpec]:
    """Build the Priority 1 EO fixture specifications."""
    # optical_rgb_small — 3-band uint8 RGB.
    rgb = [
        _ramp(0).astype("uint8"),
        _ramp(64).astype("uint8"),
        _ramp(128).astype("uint8"),
    ]

    # multispectral_s2_like_small — 4-band uint16 (B, G, R, NIR) reflectance.
    ms = [(_ramp(s) * 40).astype("uint16") for s in (10, 20, 30, 40)]

    # water_mask_small — single-band uint8 binary mask (0/1) with nodata 255.
    mask = np.zeros((_SIZE, _SIZE), dtype="uint8")
    mask[4:12, 4:12] = 1
    mask[0, 0] = 255  # one nodata pixel

    # dem_small — single-band float32 elevation with a NaN nodata pixel.
    dem = (_ramp(0).astype("float32") * 3.5) + 100.0
    dem[15, 15] = np.nan

    # ndvi_small — single-band float32 in [-1, 1].
    ndvi = ((_ramp(0).astype("float32") / 255.0) * 2.0) - 1.0

    return [
        RasterSpec(
            case_id="optical_rgb_small",
            primary="optical_rgb_small.tif",
            bands=rgb,
            dtype="uint8",
            band_names=["red", "green", "blue"],
            compression="deflate",
        ),
        RasterSpec(
            case_id="multispectral_s2_like_small",
            primary="multispectral_s2_like_small.tif",
            bands=ms,
            dtype="uint16",
            nodata=0,
            band_names=["blue", "green", "red", "nir"],
            compression="deflate",
        ),
        RasterSpec(
            case_id="water_mask_small",
            primary="water_mask_small.tif",
            bands=[mask],
            dtype="uint8",
            nodata=255,
            band_names=["water"],
            compression="deflate",
        ),
        RasterSpec(
            case_id="dem_small",
            primary="dem_small.tif",
            bands=[dem],
            dtype="float32",
            nodata=float("nan"),
            band_names=["elevation"],
            compression="deflate",
        ),
        RasterSpec(
            case_id="ndvi_small",
            primary="ndvi_small.tif",
            bands=[ndvi],
            dtype="float32",
            band_names=["ndvi"],
            compression="deflate",
        ),
    ]


def _write_raster(spec: RasterSpec, dest: Path) -> None:
    """Write *spec* to *dest* with explicit, deterministic profile."""
    array = spec.array()
    profile = {
        "driver": "GTiff",
        "height": _SIZE,
        "width": _SIZE,
        "count": array.shape[0],
        "dtype": spec.dtype,
        "crs": _CRS,
        "transform": _TRANSFORM,
    }
    if spec.nodata is not None:
        profile["nodata"] = spec.nodata
    if spec.compression is not None:
        profile["compress"] = spec.compression

    dest.parent.mkdir(parents=True, exist_ok=True)
    with rasterio.open(dest, "w", **profile) as dst:
        dst.write(array)
        if spec.band_names:
            for idx, name in enumerate(spec.band_names, start=1):
                dst.set_band_description(idx, name)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate bundled raster fixtures.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any fixture would change instead of writing it.",
    )
    parser.add_argument(
        "--raster-root",
        type=Path,
        default=RASTER_ROOT,
        help="Root directory for raster case folders.",
    )
    return parser.parse_args()


def main() -> int:
    """CLI entrypoint."""
    args = parse_args()
    specs = _specs()

    if args.check:
        import tempfile

        stale: list[str] = []
        for spec in specs:
            dest = args.raster_root / spec.case_id / spec.primary
            if not dest.exists():
                stale.append(spec.case_id)
                continue
            with tempfile.TemporaryDirectory() as tmp:
                candidate = Path(tmp) / spec.primary
                _write_raster(spec, candidate)
                if candidate.read_bytes() != dest.read_bytes():
                    stale.append(spec.case_id)
        if stale:
            print(f"Raster fixtures out of date: {', '.join(stale)}")
            return 1
        print("All raster fixtures up to date")
        return 0

    for spec in specs:
        dest = args.raster_root / spec.case_id / spec.primary
        _write_raster(spec, dest)
        print(f"Wrote {dest.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
