"""Generate the public catalog pages for the documentation site.

Reads every registered case through the catalog registry and emits, under
``docs/_generated/catalog/``:

- ``index.md``            -- catalog landing page with grouped listings,
- ``cases/<case_id>.md``  -- one page per case, with ``schema.org/Dataset`` JSON-LD,
- ``risk/<slug>.md``      -- hub page per risk type,
- ``format/<slug>.md``    -- hub page per format.

The per-case pages carry the JSON-LD that makes the catalog eligible for
Google Dataset Search, so they are the main SEO surface of the site.

Use ``--check`` in CI to assert the committed output is up to date.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
OUTPUT_ROOT = REPO_ROOT / "docs" / "_generated" / "catalog"

DEFAULT_SITE_URL = "https://farzinashouri.github.io/geocase"

if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from geocase.catalog.registry import get_registry  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))

from catalog_svg import case_diagram, case_thumbnail  # noqa: E402


# Descriptions are written for contributors, not searchers. Until they are
# rewritten, fall back through the richer prose fields before using the title.
DESCRIPTION_FIELDS = ("description", "behavioral_goal", "title")

MAX_META_DESCRIPTION = 155
MAX_RELATED_CASES = 5

# Most risk types apply to a single case. A hub page listing one row is thin
# content, so those risks stay unlinked and are surfaced on the case page and
# the catalog index instead.
MIN_HUB_CASES = 2


def _value(field: Any) -> str:
    """Return the plain string for a field that may be an enum."""
    if field is None:
        return ""
    return str(getattr(field, "value", field))


def _slug(text: str) -> str:
    """Return a URL-safe slug for a tag, risk type, or format name."""
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower())
    return slug.strip("-")


def _collapse(text: str) -> str:
    """Collapse whitespace so prose fits on a single front-matter line."""
    return " ".join(text.split())


def _meta_description(case: Any) -> str:
    """Build the SEO meta description for a case page."""
    for field in DESCRIPTION_FIELDS:
        raw = getattr(case, field, None)
        if raw:
            text = _collapse(str(raw))
            if len(text) <= MAX_META_DESCRIPTION:
                return text
            return text[: MAX_META_DESCRIPTION - 1].rstrip() + "…"
    return f"GeoCase test case {case.id}."


def _yaml_quote(text: str) -> str:
    """Quote a string for safe use as a YAML front-matter scalar."""
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _front_matter(title: str, description: str) -> list[str]:
    return [
        "---",
        f"title: {_yaml_quote(title)}",
        f"description: {_yaml_quote(description)}",
        "---",
        "",
    ]


def _generated_note() -> list[str]:
    return [
        "<!-- Generated by scripts/generate_catalog_pages.py. Do not edit by hand. -->",
        "",
    ]


def _attribute_rows(case: Any) -> list[tuple[str, str]]:
    """Return the (label, value) pairs shown in the case summary table."""
    rows: list[tuple[str, str]] = [
        ("Case ID", f"`{case.id}`"),
        ("Category", _value(case.category)),
        ("Format", _value(case.format)),
    ]
    if case.geometry_type:
        rows.append(("Geometry type", _value(case.geometry_type)))
    if case.crs:
        rows.append(("CRS", f"`{case.crs}`"))
    rows.extend(
        [
            ("Test tier", _value(case.test_tier)),
            ("Size class", _value(case.size_class)),
            ("Storage class", _value(case.storage_class)),
            ("Redistributable", "yes" if case.redistributable else "no"),
            ("Loader", f"`{_value(case.loader_hint)}`"),
        ]
    )
    status = getattr(case, "status", None)
    if status:
        rows.append(("Status", _value(status)))
    return rows


def _badges(case: Any) -> list[str]:
    """Render the case's defining facts as chips under the page title.

    These duplicate rows in the property table by design: the table is a
    reference a reader scans once, the badges are the identity of the page.
    """
    bits = [_value(case.category), _value(case.format)]
    if case.geometry_type:
        bits.append(_value(case.geometry_type))
    if case.crs:
        bits.append(case.crs)
    bits.append(_value(case.size_class))
    bits.append(_value(case.storage_class))

    chips = "".join(f'<span class="gc-badge">{bit}</span>' for bit in bits if bit)
    return ['<div class="gc-badges">', chips, "</div>", ""]


def _case_card(case: Any, href: str) -> list[str]:
    """Render one case as a thumbnail card for a grid listing."""
    meta = _value(case.format)
    geom = _value(case.geometry_type)
    if geom:
        meta = f"{meta} &middot; {geom}"
    return [
        f'<a class="gc-card" href="{href}">',
        case_thumbnail(case),
        f'<span class="gc-card-title">{case.title}</span>',
        f'<span class="gc-card-meta">{meta}</span>',
        "</a>",
    ]


def _case_grid(cases: list[Any], href_prefix: str) -> list[str]:
    """Render a grid of case cards, skipping cases with no drawable schematic.

    ``href_prefix`` must be a *resolved* URL prefix, not a Markdown path.
    These anchors are raw HTML, so mkdocs does not rewrite ``.md`` targets
    inside them the way it does for Markdown links -- emitting ``foo.md`` here
    ships a broken link that ``mkdocs build --strict`` will not catch.
    """
    cards: list[str] = []
    for case in cases:
        if not case_thumbnail(case):
            continue
        cards.extend(_case_card(case, f"{href_prefix}{case.id}/"))
    if not cards:
        return []
    return ['<div class="gc-grid">', *cards, "</div>", ""]


def _assertion_rows(case: Any) -> list[tuple[str, str]]:
    """Return the populated assertion hints as (label, value) pairs."""
    assertions = getattr(case, "assertions", None)
    if assertions is None:
        return []

    dumped = assertions.model_dump(exclude_none=True)
    rows: list[tuple[str, str]] = []
    for key, value in dumped.items():
        if isinstance(value, list):
            if not value:
                continue
            if all(isinstance(item, int) for item in value):
                # Shapes and band counts read better as a single literal.
                rendered = f"`{list(value)}`"
            else:
                rendered = ", ".join(f"`{item}`" for item in value)
        elif isinstance(value, bool):
            rendered = "yes" if value else "no"
        else:
            rendered = f"`{_value(value)}`"
        rows.append((f"`{key}`", rendered))
    return rows


def _table(headers: tuple[str, str], rows: list[tuple[str, str]]) -> list[str]:
    lines = [f"| {headers[0]} | {headers[1]} |", "|---|---|"]
    lines.extend(f"| {left} | {right} |" for left, right in rows)
    return lines


def _related_cases(case: Any, all_cases: list[Any]) -> list[Any]:
    """Return cases sharing the most tags and risk types with ``case``."""
    own_tags = set(case.tags)
    own_risks = set(case.risk_types)

    scored: list[tuple[int, str, Any]] = []
    for other in all_cases:
        if other.id == case.id:
            continue
        # Risk overlap is the stronger signal: it is what a reader browsing one
        # failure mode actually wants to see next.
        score = 2 * len(own_risks & set(other.risk_types)) + len(
            own_tags & set(other.tags)
        )
        if _value(other.category) == _value(case.category):
            score += 1
        if score > 0:
            scored.append((-score, other.id, other))

    scored.sort(key=lambda entry: (entry[0], entry[1]))
    return [entry[2] for entry in scored[:MAX_RELATED_CASES]]


def _json_ld(case: Any, site_url: str) -> list[str]:
    """Build the schema.org/Dataset JSON-LD block for a case page."""
    case_url = f"{site_url}/_generated/catalog/cases/{case.id}/"
    source = getattr(case, "source", None)

    payload: dict[str, Any] = {
        "@context": "https://schema.org",
        "@type": "Dataset",
        "name": case.title,
        "description": _collapse(
            str(case.description or case.behavioral_goal or case.title)
        ),
        "identifier": case.id,
        "url": case_url,
        "isPartOf": {
            "@type": "DataCatalog",
            "name": "GeoCase",
            "url": site_url,
        },
    }

    keywords = sorted(set(case.tags) | set(case.risk_types))
    if keywords:
        payload["keywords"] = keywords

    if source is not None:
        if source.license:
            payload["license"] = source.license
        if source.name:
            payload["creator"] = {"@type": "Organization", "name": source.name}
        if source.url:
            payload["isBasedOn"] = source.url

    primary = getattr(case.files, "primary", None)
    if primary:
        payload["distribution"] = [
            {
                "@type": "DataDownload",
                "encodingFormat": _value(case.format),
                "name": primary,
            }
        ]

    if case.crs:
        payload["spatialCoverage"] = {
            "@type": "Place",
            "additionalProperty": {
                "@type": "PropertyValue",
                "name": "coordinateReferenceSystem",
                "value": case.crs,
            },
        }

    rendered = json.dumps(payload, indent=2, ensure_ascii=False)
    return ['<script type="application/ld+json">', rendered, "</script>", ""]


def _render_case_page(
    case: Any, all_cases: list[Any], site_url: str, hub_risks: set[str]
) -> str:
    """Render the full markdown page for a single case."""
    lines = _front_matter(case.title, _meta_description(case))
    lines.extend(_generated_note())
    lines.append(f"# {case.title}")
    lines.append("")

    lines.extend(_badges(case))

    if case.description:
        lines.append(_collapse(case.description))
        lines.append("")

    # The schematic sits above the tables: it answers "what shape of thing is
    # this?" in one glance, which is the question the tables answer slowly.
    lines.extend(case_diagram(case))

    lines.extend(_table(("Property", "Value"), _attribute_rows(case)))
    lines.append("")

    lines.append("## Use this case")
    lines.append("")
    lines.append("```python")
    lines.append("import pytest")
    lines.append("")
    lines.append("")
    lines.append(f'@pytest.mark.geocase_case("{case.id}")')
    lines.append(f"def test_{case.id}(geocase_case) -> None:")
    lines.append("    data = geocase_case.load()")
    lines.append("    assert data is not None")
    lines.append("```")
    lines.append("")

    if case.behavioral_goal:
        lines.append("## What this case checks")
        lines.append("")
        lines.append(_collapse(case.behavioral_goal))
        lines.append("")

    if case.risk_types:
        lines.append("## Risk types covered")
        lines.append("")
        for risk in sorted(case.risk_types):
            if risk in hub_risks:
                # Case pages live at ``catalog/cases/<id>.md`` and risk hubs at
                # ``catalog/risk/<slug>.md``, so the hop is one level, not two.
                lines.append(f"- [`{risk}`](../risk/{_slug(risk)}.md)")
            else:
                lines.append(f"- `{risk}`")
        lines.append("")

    assertion_rows = _assertion_rows(case)
    if assertion_rows:
        lines.append("## Expected behavior")
        lines.append("")
        lines.extend(_table(("Assertion", "Expected"), assertion_rows))
        lines.append("")

    if case.expected_capabilities:
        lines.append("## Required capabilities")
        lines.append("")
        for capability in case.expected_capabilities:
            lines.append(f"- `{capability}`")
        lines.append("")

    lines.append("## Files")
    lines.append("")
    lines.append(f"- Primary: `{case.files.primary}`")
    for sidecar in getattr(case.files, "sidecars", []):
        lines.append(f"- Sidecar: `{sidecar}`")
    if getattr(case.files, "notes", None):
        lines.append(f"- Notes: {_collapse(case.files.notes)}")
    lines.append("")

    source = getattr(case, "source", None)
    if source is not None and (source.name or source.license or source.url):
        lines.append("## Source and license")
        lines.append("")
        if source.name:
            lines.append(f"- Source: {source.name}")
        if source.license:
            lines.append(f"- License: {source.license}")
        if source.url:
            lines.append(f"- URL: <{source.url}>")
        if source.derived_from:
            lines.append(f"- Derived from: {source.derived_from}")
        lines.append("")

    if case.tags:
        lines.append("## Tags")
        lines.append("")
        lines.append(" ".join(f"`{tag}`" for tag in sorted(case.tags)))
        lines.append("")

    related = _related_cases(case, all_cases)
    if related:
        lines.append("## Related cases")
        lines.append("")
        for other in related:
            lines.append(f"- [{other.title}]({other.id}.md) -- `{other.id}`")
        lines.append("")

    lines.extend(_json_ld(case, site_url))
    return "\n".join(lines).rstrip() + "\n"


def _render_hub_page(
    *,
    title: str,
    description: str,
    intro: str,
    cases: list[Any],
    link_prefix: str,
) -> str:
    """Render a hub page listing every case under one facet value."""
    lines = _front_matter(title, description)
    lines.extend(_generated_note())
    lines.append(f"# {title}")
    lines.append("")
    lines.append(intro)
    lines.append("")

    # The grid first, then the table. Someone landing on a risk hub is asking
    # "what kind of data trips this?" -- the schematics answer that before the
    # table's names do.
    # Hub pages render at /catalog/<facet>/<slug>/, so cases sit two levels up.
    lines.extend(_case_grid(sorted(cases, key=lambda item: item.id), "../../cases/"))

    lines.append("| Case | Category | Format | Geometry |")
    lines.append("|---|---|---|---|")
    for case in sorted(cases, key=lambda item: item.id):
        geometry = _value(case.geometry_type) or "--"
        lines.append(
            f"| [{case.title}]({link_prefix}{case.id}.md) "
            f"| {_value(case.category)} | {_value(case.format)} | {geometry} |"
        )
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _render_index(
    cases: list[Any],
    by_risk: dict[str, list[Any]],
    by_format: dict[str, list[Any]],
    hub_risks: set[str],
) -> str:
    """Render the catalog landing page."""
    by_category: dict[str, list[Any]] = defaultdict(list)
    for case in cases:
        by_category[_value(case.category)].append(case)

    lines = _front_matter(
        "Case Catalog",
        f"Browse all {len(cases)} curated GeoCase test cases by category, format, and risk type.",
    )
    lines.extend(_generated_note())
    lines.append("# Case Catalog")
    lines.append("")
    lines.append(
        f"GeoCase ships {len(cases)} curated geospatial test cases. "
        "Every case is addressable by ID from a plain `pytest` test."
    )
    lines.append("")

    lines.append("## Reading the schematics")
    lines.append("")
    lines.append(
        "Each case page carries a diagram of the case's *structure*: the geometry type "
        "for vector cases, and the band stack, pixel grid, and NoData marker for raster "
        "cases."
    )
    lines.append("")
    lines.append('!!! warning "Schematics are not pictures of the data"')
    lines.append("")
    lines.append(
        "    They are drawn from case metadata alone -- never from the fixture bytes. "
        "A `Polygon` schematic shows *a* polygon, not the case's real coordinates, and "
        "a raster grid shows *that* there are pixels, not their values. Load the case "
        "to see the actual data."
    )
    lines.append("")

    lines.append("## Browse by risk type")
    lines.append("")
    lines.append("Start here if you know the failure mode you want to test against.")
    lines.append("")
    lines.append("| Risk type | Cases |")
    lines.append("|---|---:|")
    for risk in sorted(hub_risks):
        lines.append(f"| [`{risk}`](risk/{_slug(risk)}.md) | {len(by_risk[risk])} |")
    lines.append("")
    lines.append(
        f"A further {len(by_risk) - len(hub_risks)} risk types apply to a single case "
        "and are listed against each case below."
    )
    lines.append("")

    lines.append("## Browse by format")
    lines.append("")
    lines.append("| Format | Cases |")
    lines.append("|---|---:|")
    for fmt in sorted(by_format):
        lines.append(f"| [{fmt}](format/{_slug(fmt)}.md) | {len(by_format[fmt])} |")
    lines.append("")

    lines.append("## All cases by category")
    lines.append("")
    for category in sorted(by_category):
        entries = sorted(by_category[category], key=lambda item: item.id)
        lines.append(f"### {category} ({len(entries)})")
        lines.append("")
        lines.append("| Case | Format | Geometry | Risk types |")
        lines.append("|---|---|---|---|")
        for case in entries:
            geometry = _value(case.geometry_type) or "--"
            risks = ", ".join(f"`{risk}`" for risk in sorted(case.risk_types)) or "--"
            lines.append(
                f"| [{case.title}](cases/{case.id}.md) "
                f"| {_value(case.format)} | {geometry} | {risks} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def build_pages(cases: list[Any], site_url: str) -> dict[str, str]:
    """Build every catalog page as a mapping of relative path to content."""
    by_risk: dict[str, list[Any]] = defaultdict(list)
    by_format: dict[str, list[Any]] = defaultdict(list)
    for case in cases:
        for risk in case.risk_types:
            by_risk[risk].append(case)
        by_format[_value(case.format)].append(case)

    hub_risks = {
        risk for risk, entries in by_risk.items() if len(entries) >= MIN_HUB_CASES
    }

    pages: dict[str, str] = {
        "index.md": _render_index(cases, by_risk, by_format, hub_risks),
    }

    for case in cases:
        pages[f"cases/{case.id}.md"] = _render_case_page(
            case, cases, site_url, hub_risks
        )

    for risk in sorted(hub_risks):
        entries = by_risk[risk]
        pages[f"risk/{_slug(risk)}.md"] = _render_hub_page(
            title=f"Risk type: {risk}",
            description=(
                f"{len(entries)} GeoCase test cases that exercise the "
                f"{risk.replace('_', ' ')} failure mode."
            ),
            intro=(
                f"These {len(entries)} cases exercise the `{risk}` failure mode. "
                "Run your function against all of them to check how it behaves."
            ),
            cases=entries,
            link_prefix="../cases/",
        )

    for fmt, entries in by_format.items():
        pages[f"format/{_slug(fmt)}.md"] = _render_hub_page(
            title=f"Format: {fmt}",
            description=f"{len(entries)} GeoCase test cases available in {fmt} format.",
            intro=f"These {len(entries)} cases are packaged as {fmt}.",
            cases=entries,
            link_prefix="../cases/",
        )

    return pages


def write_pages(pages: dict[str, str], output_root: Path) -> int:
    """Write pages to disk, removing stale generated files. Returns file count."""
    if output_root.exists():
        for existing in sorted(output_root.rglob("*.md")):
            existing.unlink()

    for relative, content in sorted(pages.items()):
        target = output_root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    return len(pages)


def check_pages(pages: dict[str, str], output_root: Path) -> list[str]:
    """Return a list of human-readable drift descriptions, empty when in sync."""
    problems: list[str] = []

    for relative, content in sorted(pages.items()):
        target = output_root / relative
        if not target.exists():
            problems.append(f"missing: {relative}")
        elif target.read_text(encoding="utf-8") != content:
            problems.append(f"out of date: {relative}")

    if output_root.exists():
        expected = set(pages)
        for existing in sorted(output_root.rglob("*.md")):
            relative = existing.relative_to(output_root).as_posix()
            if relative not in expected:
                problems.append(f"stale: {relative}")

    return problems


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate catalog documentation pages."
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=OUTPUT_ROOT,
        help="Directory to write generated catalog pages into.",
    )
    parser.add_argument(
        "--site-url",
        default=DEFAULT_SITE_URL,
        help="Canonical site URL used in JSON-LD.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the committed pages match the catalog instead of writing them.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    cases = sorted(get_registry().list_cases(), key=lambda case: case.id)
    if not cases:
        print("No cases found in the registry.")
        return 1

    pages = build_pages(cases, args.site_url.rstrip("/"))

    if args.check:
        problems = check_pages(pages, args.output_root)
        if problems:
            print(f"Catalog pages are out of date ({len(problems)} problem(s)):")
            for problem in problems:
                print(f"  - {problem}")
            print("\nRegenerate with: python scripts/generate_catalog_pages.py")
            return 1
        print(f"Catalog pages are up to date ({len(pages)} files, {len(cases)} cases).")
        return 0

    written = write_pages(pages, args.output_root)
    print(f"Wrote {written} catalog pages for {len(cases)} cases to {args.output_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
