"""Reproducible generator for bundled raster fixtures.

Implements Steps 3 and 4 of ``docs/plans/archive/08-raster-action-plan.md``: each
fixture is built from a deterministic numpy array with explicit metadata
(CRS, transform, dtype, nodata, band names, compression) so the committed
GeoTIFFs can be regenerated byte-stably instead of being opaque blobs.

Usage::

    python scripts/generate_raster_fixtures.py            # write all fixtures
    python scripts/generate_raster_fixtures.py --check    # verify up to date

The generator only writes the ``.tif`` primary files. Case metadata
(``case.yaml`` / ``notes.md``) is authored alongside and indexed via
``scripts/build_case_index.py``.

Plan 18 Phase 1: the four S2/S1 product fixtures are no longer thin
``RasterSpec`` ramps — they are emitted by ``geocase.raster.presets``, whose facts
are machine-checked against real granule metadata
(the geofacts package). The ``--check`` byte-stability gate
covers them identically.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
import rasterio
from rasterio.enums import Resampling
from rasterio.transform import Affine, from_origin

REPO_ROOT = Path(__file__).resolve().parents[1]
RASTER_ROOT = REPO_ROOT / "src" / "geocase" / "data" / "core" / "raster"

# A small UTM-like transform shared by the synthetic scenes (10 m pixels).
_TRANSFORM = from_origin(500000.0, 4500000.0, 10.0, 10.0)
_CRS = "EPSG:32633"
_SIZE = 16


@dataclass
class RasterSpec:
    """Declarative description of a synthetic raster fixture."""

    case_id: str
    primary: str
    bands: list[np.ndarray]
    dtype: str
    nodata: float | int | None = None
    band_names: list[str] = field(default_factory=list)
    compression: str | None = None
    # Folder holding the fixture, when it is not ``<raster_root>/<case_id>``.
    # The footprint edge cases share one directory (see _footprint_edge_specs).
    case_dir: str | None = None
    # Emit ``<stem>_footprint_truth.geojson`` derived from this fixture's own
    # nodata mask, so the footprint cannot drift away from the pixels it
    # describes.
    emit_footprint: bool = False
    # CRS / transform overrides for geography-specific scenes.
    crs: str = _CRS
    transform: Any | None = None
    # COG-style / overview controls.
    tiled: bool = False
    block_size: int = 16
    overviews: list[int] = field(default_factory=list)
    external_overviews: bool = False
    # Per-dataset band scale factor (e.g. scaled int16 reflectance).
    scale_factor: float | None = None
    # Single-band categorical colormap: {value: (r, g, b, a)}.
    colormap: dict[int, tuple[int, int, int, int]] | None = None

    def array(self) -> np.ndarray:
        return np.stack(self.bands).astype(self.dtype)

    def resolved_transform(self) -> Any:
        return self.transform if self.transform is not None else _TRANSFORM


def _ramp(seed: int) -> np.ndarray:
    """Deterministic 16x16 gradient array, offset by *seed*."""
    rows = np.arange(_SIZE).reshape(-1, 1)
    cols = np.arange(_SIZE).reshape(1, -1)
    return (rows + cols + seed) % 256


def _specs() -> list[RasterSpec]:
    """Build the Priority 1 EO fixture specifications."""
    # optical_rgb_small — 3-band uint8 RGB.
    rgb = [
        _ramp(0).astype("uint8"),
        _ramp(64).astype("uint8"),
        _ramp(128).astype("uint8"),
    ]

    # water_mask_small — single-band uint8 binary mask (0/1) with nodata 255.
    mask = np.zeros((_SIZE, _SIZE), dtype="uint8")
    mask[4:12, 4:12] = 1
    mask[0, 0] = 255  # one nodata pixel

    # dem_small — single-band float32 elevation with a NaN nodata pixel.
    dem = (_ramp(0).astype("float32") * 3.5) + 100.0
    dem[15, 15] = np.nan

    # ndvi_small — single-band float32 in [-1, 1].
    ndvi = ((_ramp(0).astype("float32") / 255.0) * 2.0) - 1.0

    return [
        RasterSpec(
            case_id="optical_rgb_small",
            primary="optical_rgb_small.tif",
            bands=rgb,
            dtype="uint8",
            band_names=["red", "green", "blue"],
            compression="deflate",
        ),
        # multispectral_s2_like_small moved to _synth_specs() (Plan 18).
        RasterSpec(
            case_id="water_mask_small",
            primary="water_mask_small.tif",
            bands=[mask],
            dtype="uint8",
            nodata=255,
            band_names=["water"],
            compression="deflate",
        ),
        RasterSpec(
            case_id="dem_small",
            primary="dem_small.tif",
            bands=[dem],
            dtype="float32",
            nodata=float("nan"),
            band_names=["elevation"],
            compression="deflate",
        ),
        RasterSpec(
            case_id="ndvi_small",
            primary="ndvi_small.tif",
            bands=[ndvi],
            dtype="float32",
            band_names=["ndvi"],
            compression="deflate",
        ),
        *_priority_2_4_specs(),
        *_footprint_edge_specs(),
    ]


def _priority_2_4_specs() -> list[RasterSpec]:
    """Build the Priority 2–4 raster families (Step 9 of the action plan)."""
    from rasterio.transform import Affine, from_origin as _origin

    # -- Priority 2: COG / overviews / compression ------------------------
    # COG scenes are 64x64 so a 16px internal tiling actually registers
    # (a 16x16 scene fits in a single block and GDAL stores it untiled).
    def _ramp64(seed: int) -> np.ndarray:
        rows = np.arange(64).reshape(-1, 1)
        cols = np.arange(64).reshape(1, -1)
        return (rows + cols + seed) % 256

    cog_single = [(_ramp64(5) * 20).astype("uint16")]
    cog_ms = [(_ramp64(s) * 30).astype("uint16") for s in (10, 20, 30, 40)]
    # Declares nodata=0 and shipped with none of it, so tile/overview reads
    # never crossed a nodata boundary (Plan 28 Phase 1.5). A 1 px frame is what
    # a real reprojected scene carries, and it is what makes the COG's
    # overview-vs-decimated nodata handling observable at all.
    for band in cog_ms:
        band[0, :] = 0
        band[-1, :] = 0
        band[:, 0] = 0
        band[:, -1] = 0
    ovr_band = [(_ramp64(7)).astype("uint8")]

    # -- Priority 3: SAR + geography --------------------------------------
    # SAR scenes moved to _synth_specs() (Plan 18): real GRD is uint16
    # detected amplitude with a zero border, not clean float32.
    optical = [
        _ramp(0).astype("uint8"),
        _ramp(64).astype("uint8"),
        _ramp(128).astype("uint8"),
    ]
    # Geographic (lon/lat) transforms with ~0.01 deg pixels.
    polar_tx = _origin(-2_000_000.0, 2_000_000.0, 10.0, 10.0)  # EPSG:3995 metres
    dateline_tx = _origin(179.9, 1.0, 0.02, 0.02)  # straddles +180 lon
    equator_tx = _origin(10.0, 0.16, 0.01, 0.01)  # centred on the equator

    # -- Priority 4: mixed resolution / NaN DEM / scaled NDVI / landcover --
    # multispectral_mixed_resolution_small moved to _synth_specs() (Plan 18):
    # the old version resampled all bands to one grid, so no mismatch existed.
    dem_nan = (_ramp(0).astype("float32") * 4.0) + 50.0
    dem_nan[0, 0] = np.nan
    dem_nan[15, 15] = np.nan
    # Scaled int16 NDVI: physical NDVI in [-1, 1] stored as int16 * 1e-4.
    ndvi_phys = ((_ramp(0).astype("float32") / 255.0) * 2.0) - 1.0
    ndvi_int16 = np.round(ndvi_phys / 1e-4).astype("int16")
    # The case exists to exercise "scaled integer with a sentinel", and was
    # inert without a single pixel at the sentinel (Plan 28 Phase 1.5). A
    # corner pixel keeps the ramp otherwise intact.
    ndvi_int16[0, 0] = -32768
    # Categorical land cover: 1=water, 2=veg, 3=urban. Deliberately *no*
    # nodata: every pixel is classified, and 0 doubling as both a class and a
    # sentinel is the ``ambiguous_zero`` risk, which gets its own explicit case
    # below rather than a silent declaration here (Plan 28 Phase 1.5).
    landcover = np.zeros((_SIZE, _SIZE), dtype="uint8")
    landcover[:8, :8] = 1
    landcover[:8, 8:] = 2
    landcover[8:, :8] = 3
    landcover[8:, 8:] = 2
    landcover_cmap = {
        0: (0, 0, 0, 0),
        1: (0, 0, 255, 255),
        2: (0, 200, 0, 255),
        3: (128, 128, 128, 255),
    }

    # landcover_ambiguous_zero_small -- the sibling scene, with the ambiguity
    # put back deliberately (Plan 32 Phase 2). Same three classes, plus class 0
    # ("unclassified / bare") occupying a real region, and ``nodata=0``
    # declared on top of it. Nothing in the file distinguishes the two
    # meanings: a consumer masking ``data == nodata`` deletes every class-0
    # pixel, and a consumer ignoring nodata treats sentinel pixels as a class.
    # That indistinguishability *is* the case.
    landcover_ambiguous = landcover.copy()
    landcover_ambiguous[4:12, 4:12] = 0

    return [
        RasterSpec(
            case_id="cog_singleband_small",
            primary="cog_singleband_small.tif",
            bands=cog_single,
            dtype="uint16",
            band_names=["intensity"],
            compression="deflate",
            tiled=True,
            overviews=[2],
        ),
        RasterSpec(
            case_id="cog_multispectral_small",
            primary="cog_multispectral_small.tif",
            bands=cog_ms,
            dtype="uint16",
            nodata=0,
            band_names=["blue", "green", "red", "nir"],
            compression="deflate",
            tiled=True,
            overviews=[2],
        ),
        RasterSpec(
            case_id="geotiff_external_overviews_small",
            primary="geotiff_external_overviews_small.tif",
            bands=ovr_band,
            dtype="uint8",
            band_names=["gray"],
            compression="deflate",
            overviews=[2],
            external_overviews=True,
        ),
        RasterSpec(
            case_id="optical_polar_small",
            primary="optical_polar_small.tif",
            bands=optical,
            dtype="uint8",
            band_names=["red", "green", "blue"],
            compression="deflate",
            crs="EPSG:3995",
            transform=polar_tx,
        ),
        RasterSpec(
            case_id="optical_dateline_small",
            primary="optical_dateline_small.tif",
            bands=optical,
            dtype="uint8",
            band_names=["red", "green", "blue"],
            compression="deflate",
            crs="EPSG:4326",
            transform=dateline_tx,
        ),
        RasterSpec(
            case_id="optical_equator_small",
            primary="optical_equator_small.tif",
            bands=optical,
            dtype="uint8",
            band_names=["red", "green", "blue"],
            compression="deflate",
            crs="EPSG:4326",
            transform=equator_tx,
        ),
        RasterSpec(
            case_id="dem_nan_nodata_small",
            primary="dem_nan_nodata_small.tif",
            bands=[dem_nan],
            dtype="float32",
            nodata=float("nan"),
            band_names=["elevation"],
            compression="deflate",
        ),
        RasterSpec(
            case_id="ndvi_scaled_int16_small",
            primary="ndvi_scaled_int16_small.tif",
            bands=[ndvi_int16],
            dtype="int16",
            nodata=-32768,
            band_names=["ndvi"],
            compression="deflate",
            scale_factor=1e-4,
        ),
        RasterSpec(
            case_id="landcover_small",
            primary="landcover_small.tif",
            bands=[landcover],
            dtype="uint8",
            band_names=["landcover"],
            compression="deflate",
            colormap=landcover_cmap,
        ),
        RasterSpec(
            case_id="landcover_ambiguous_zero_small",
            primary="landcover_ambiguous_zero_small.tif",
            bands=[landcover_ambiguous],
            dtype="uint8",
            nodata=0,
            band_names=["landcover"],
            compression="deflate",
            colormap=landcover_cmap,
        ),
    ]


#: Directory shared by every footprint edge case.
_FOOTPRINT_DIR = "footprint_edge_cases"


def _footprint_edge_specs() -> list[RasterSpec]:
    """The footprint edge cases, raster *and* footprint from one array.

    These were hand-committed and sat outside the only regeneration gate, which
    is how ``hole_center_nodata`` came to be the exact inverse of its own
    description: it claims valid pixels ringing a central NoData void, and
    shipped with nodata on the 1 px outer border and a fully valid interior.
    Its committed footprint had been regenerated from the drifted raster, so the
    two agreed with each other and disagreed only with the case's stated purpose
    -- invisible to any check that compares declarations to declarations.

    Deriving both artifacts from the same array here means the footprint is
    correct by construction and the drift cannot recur (Plan 28 Phase 1.5).
    """
    fill = 100.0
    nd = -9999.0

    # hole_center_nodata -- the shape the case has always claimed: an interior
    # void, fully enclosed by valid pixels. The border stays valid, which is
    # what makes footprint extraction that ignores nodata visibly wrong (it
    # returns the solid 12x12 rectangle instead of a ring).
    hole = np.full((12, 12), fill, dtype="float32")
    hole[4:8, 4:8] = nd

    # all_valid_rectangular -- the control: no invalid pixel anywhere. It
    # declares no nodata expectation and must not gain one.
    all_valid = np.full((12, 12), fill, dtype="float32")

    # nonsquare_diagonal_sparse -- non-square pixels (60x30 m) plus a diagonal
    # run of valid pixels touching only at corners, so a footprint built in
    # pixel space rather than world space comes out with the wrong aspect ratio.
    diagonal = np.full((8, 8), nd, dtype="float32")
    diagonal[np.arange(8), np.arange(8)] = fill

    # rotated_two_islands -- two disjoint blobs under a rotated transform: the
    # footprint must be a MultiPolygon, and must be rotated with the grid.
    islands = np.full((8, 8), nd, dtype="float32")
    islands[0:3, 0:3] = fill
    islands[4:8, 5:8] = fill

    # thin_corridor_shape -- 1 px-wide arms, which simplification tolerances
    # tend to collapse to nothing.
    corridor = np.full((14, 14), nd, dtype="float32")
    corridor[2:12, 3] = fill
    corridor[4, 3:9] = fill
    corridor[10, 3:11] = fill

    def _spec(
        case_id: str,
        array: np.ndarray,
        transform: Any,
        *,
        emit_footprint: bool = False,
    ) -> RasterSpec:
        return RasterSpec(
            case_id=case_id,
            primary=f"{case_id}.tif",
            bands=[array],
            dtype="float32",
            nodata=nd,
            transform=transform,
            case_dir=_FOOTPRINT_DIR,
            emit_footprint=emit_footprint,
        )

    # Every case emits its own mask-exact ``_footprint_truth.geojson`` (Plan 32
    # Phase 1.2). The hand-committed files these replace were recordings of
    # ``gdal_footprint``'s simplified/convex-hull answer -- for
    # ``rotated_two_islands`` a single polygon spanning the gap between two
    # disjoint islands, 1.98x the true area. Those recordings survive, renamed
    # to ``_footprint_gdal_hull.geojson`` and pointed at by
    # ``params.recorded_gdal_footprint``, so GDAL's behaviour stays under a
    # regression check without being mistaken for truth. ``all_valid_rectangular``
    # gets no hull file: a full rectangle *is* its own convex hull, so the two
    # would be byte-identical and the second file would carry no information.
    return [
        _spec(
            "hole_center_nodata",
            hole,
            from_origin(400000.0, 4300000.0, 30.0, 30.0),
            emit_footprint=True,
        ),
        _spec(
            "all_valid_rectangular",
            all_valid,
            from_origin(500000.0, 4200000.0, 30.0, 30.0),
            emit_footprint=True,
        ),
        _spec(
            "nonsquare_diagonal_sparse",
            diagonal,
            from_origin(250000.0, 4600000.0, 60.0, 30.0),
            emit_footprint=True,
        ),
        # A genuinely rotated affine: the b/d terms are non-zero.
        _spec(
            "rotated_two_islands",
            islands,
            Affine(20.0, 5.0, 1000.0, -5.0, -20.0, 2000.0),
            emit_footprint=True,
        ),
        _spec(
            "thin_corridor_shape",
            corridor,
            from_origin(700000.0, 5100000.0, 25.0, 25.0),
            emit_footprint=True,
        ),
    ]


def _write_footprint(spec: RasterSpec, raster_path: Path) -> Path:
    """Derive ``<stem>_footprint_truth.geojson`` from the raster's valid mask.

    The ``_truth`` suffix is load-bearing (Plan 32 Phase 1.2). The folder also
    ships ``<stem>_footprint_gdal_hull.geojson`` for three of these cases: a
    *recording of ``gdal_footprint``'s own simplified/hull output*, kept so a
    change in GDAL's behaviour stays detectable but never mistaken for ground
    truth. Only this file is mask-exact, and only this file is what
    ``params.expected_footprint`` points at.
    """
    import json

    import rasterio.features
    from shapely.geometry import mapping, shape
    from shapely.ops import unary_union

    with rasterio.open(raster_path) as src:
        mask = src.dataset_mask()
        crs = src.crs
        polygons = [
            shape(geom)
            for geom, value in rasterio.features.shapes(
                mask, mask=mask.astype(bool), transform=src.transform
            )
            if value != 0
        ]

    merged = unary_union(polygons)
    dest = raster_path.with_name(f"{raster_path.stem}_footprint_truth.geojson")
    payload = {
        "type": "FeatureCollection",
        "name": f"{spec.case_id}_footprint_truth",
        "crs": {
            "type": "name",
            "properties": {"name": crs.to_string()},
        },
        "features": [
            {
                "type": "Feature",
                "properties": {"case_id": spec.case_id},
                "geometry": mapping(merged),
            }
        ],
    }
    dest.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    return dest


@dataclass
class SynthSpec:
    """A fixture emitted by ``geocase.raster.presets`` instead of a raw ramp."""

    case_id: str
    primary: str
    build: Any  # Callable[[Path], Any]; typed loosely to keep the CLI light.


def _synth_specs() -> list[SynthSpec]:
    """Product fixtures regenerated from the audited generator (Plan 18)."""
    from geocase.raster.presets import sentinel1_grd, sentinel2_l2a

    return [
        # Real L2A radiometry: nodata 0, scale 1e-4 / offset -0.1 on the
        # bands, BOA_ADD_OFFSET / QUANTIFICATION_VALUE / PROCESSING_BASELINE
        # tags, band names B02/B03/B04/B08.
        # ``nodata_border=1`` is not decoration: both fixtures declare
        # ``expect_nodata`` and a nodata value of 0, and both shipped with zero
        # pixels taking it, so every nodata-handling probe run against them
        # passed vacuously. Real L2A granules carry a nodata frame; the content
        # gate (Plan 28 Phase 1) now requires the declaration to be backed by
        # actual pixels.
        SynthSpec(
            case_id="multispectral_s2_like_small",
            primary="multispectral_s2_like_small.tif",
            build=lambda p: sentinel2_l2a(p, size=_SIZE, nodata_border=1),
        ),
        # A mismatch that actually exists: B11 is 20 m-native, carried on the
        # 10 m grid as 2x2 block-replicated values.
        SynthSpec(
            case_id="multispectral_mixed_resolution_small",
            primary="multispectral_mixed_resolution_small.tif",
            build=lambda p: sentinel2_l2a(
                p, size=_SIZE, bands=("B04", "B08", "B11"), nodata_border=1
            ),
        ),
        # Real GRD: uint16 detected amplitude, zero border noise, nodata 0.
        SynthSpec(
            case_id="sar_vv_small",
            primary="sar_vv_small.tif",
            build=lambda p: sentinel1_grd(p, size=_SIZE, pol="VV", border_noise=True),
        ),
        SynthSpec(
            case_id="sar_dualpol_small",
            primary="sar_dualpol_small.tif",
            build=lambda p: sentinel1_grd(
                p, size=_SIZE, pol="VV+VH", border_noise=True
            ),
        ),
    ]


def _write_raster(spec: RasterSpec, dest: Path) -> None:
    """Write *spec* to *dest* with explicit, deterministic profile."""
    array = spec.array()
    height, width = array.shape[1], array.shape[2]
    profile = {
        "driver": "GTiff",
        "height": height,
        "width": width,
        "count": array.shape[0],
        "dtype": spec.dtype,
        "crs": spec.crs,
        "transform": spec.resolved_transform(),
    }
    if spec.nodata is not None:
        profile["nodata"] = spec.nodata
    if spec.compression is not None:
        profile["compress"] = spec.compression
    if spec.tiled:
        profile["tiled"] = True
        profile["blockxsize"] = spec.block_size
        profile["blockysize"] = spec.block_size

    # Stale external overviews would otherwise be read back transparently.
    sidecar = dest.with_suffix(dest.suffix + ".ovr")
    if sidecar.exists():
        sidecar.unlink()

    dest.parent.mkdir(parents=True, exist_ok=True)
    with rasterio.open(dest, "w", **profile) as dst:
        dst.write(array)
        if spec.band_names:
            for idx, name in enumerate(spec.band_names, start=1):
                dst.set_band_description(idx, name)
        if spec.scale_factor is not None:
            dst.scales = (spec.scale_factor,) * array.shape[0]
        if spec.colormap is not None:
            dst.write_colormap(1, spec.colormap)
        # Internal overviews (COG-style) are written inside the same file.
        if spec.overviews and not spec.external_overviews:
            dst.build_overviews(spec.overviews, Resampling.nearest)
            dst.update_tags(ns="rio_overview", resampling="nearest")

    # External overviews are built in a second pass on the read-only dataset,
    # which makes GDAL emit a sibling ``.ovr`` sidecar instead of embedding.
    if spec.overviews and spec.external_overviews:
        from osgeo import gdal

        gdal.UseExceptions()
        ds = gdal.Open(str(dest), gdal.GA_ReadOnly)
        try:
            ds.BuildOverviews("NEAREST", spec.overviews)
        finally:
            ds = None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate bundled raster fixtures.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any fixture would change instead of writing it.",
    )
    parser.add_argument(
        "--raster-root",
        type=Path,
        default=RASTER_ROOT,
        help="Root directory for raster case folders.",
    )
    return parser.parse_args()


def _emit(spec: RasterSpec | SynthSpec, dest: Path) -> list[Path]:
    """Write *spec* to *dest*; returns every file written, primary first."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(spec, SynthSpec):
        spec.build(dest)
        return [dest]

    _write_raster(spec, dest)
    written = [dest]
    if spec.emit_footprint:
        written.append(_write_footprint(spec, dest))
    return written


def _dest_for(spec: RasterSpec | SynthSpec, raster_root: Path) -> Path:
    """Resolve a spec's on-disk primary path.

    Most fixtures live in ``<raster_root>/<case_id>/``; the footprint edge
    cases share a single directory, so ``RasterSpec.case_dir`` overrides it.
    """
    folder = getattr(spec, "case_dir", None) or spec.case_id
    return raster_root / folder / spec.primary


def main() -> int:
    """CLI entrypoint."""
    args = parse_args()
    specs: list[RasterSpec | SynthSpec] = [*_specs(), *_synth_specs()]

    if args.check:
        import tempfile

        stale: list[str] = []
        for spec in specs:
            dest = _dest_for(spec, args.raster_root)
            if not dest.exists():
                stale.append(spec.case_id)
                continue
            with tempfile.TemporaryDirectory() as tmp:
                candidate = Path(tmp) / spec.primary
                for produced in _emit(spec, candidate):
                    committed = dest.with_name(produced.name)
                    if (
                        not committed.exists()
                        or produced.read_bytes() != committed.read_bytes()
                    ):
                        stale.append(spec.case_id)
                        break
        if stale:
            print(f"Raster fixtures out of date: {', '.join(stale)}")
            return 1
        print("All raster fixtures up to date")
        return 0

    for spec in specs:
        dest = _dest_for(spec, args.raster_root)
        for produced in _emit(spec, dest):
            print(f"Wrote {produced.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
