#!/usr/bin/env python
"""Publish ``CHANGELOG.md`` as ``docs/changelog.md``.

Plan 40 phase 5. The changelog is where a user lands after a break, and until
now it was not on the docs site at all -- the only route to it was a GitHub
blob link from ``[project.urls]``. That is the wrong place to send someone
whose build just went red.

``CHANGELOG.md`` stays the source of truth at the repository root, because that
is where contributors edit it and where GitHub renders it. This copies it into
``docs/`` with a frontmatter block and a provenance banner, and ``--check``
gates the copy the same way every other generated artifact is gated.

Usage::

    python scripts/generate_changelog_page.py [--check]
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "CHANGELOG.md"
TARGET = REPO_ROOT / "docs" / "changelog.md"

_FRONTMATTER = """---
description: "What changed in each GeoCase release, including every change to a case's geometry, CRS, dtype, nodata value, id or risk types, named by case id."
---

<!-- Generated by scripts/generate_changelog_page.py from CHANGELOG.md -- do not edit by hand. -->

"""


#: Repository URL for paths that have no published equivalent.
_BLOB = "https://github.com/farzinashouri/geocase/blob/main"


def render() -> str:
    body = SOURCE.read_text(encoding="utf-8")

    # The root file's links are relative to the *repository*; from docs/ they
    # do not resolve and `mkdocs build --strict` fails on every one.
    body = body.replace("](CHANGELOG.md)", "](changelog.md)")

    # `docs/foo.md` -> `foo.md`, since the page already lives in docs/. Done
    # before the blob rewrite so a published page keeps a working relative
    # link rather than being sent out to GitHub.
    body = re.sub(r"\]\(docs/([A-Za-z0-9._/-]+\.md)\)", r"](\1)", body)

    # `docs/plans/...` is excluded from the site (see mkdocs.yml exclude_docs),
    # so those must become absolute GitHub URLs or --strict fails. Same for
    # source paths and scripts, which are never published at all.
    body = re.sub(r"\]\((plans/[A-Za-z0-9._/-]+\.md)\)", rf"]({_BLOB}/docs/\1)", body)
    body = re.sub(
        r"\]\(((?:src|scripts|tests|recipe)/[A-Za-z0-9._/-]+)\)",
        rf"]({_BLOB}/\1)",
        body,
    )
    return _FRONTMATTER + body


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify docs/changelog.md is up to date; exit non-zero if not.",
    )
    args = parser.parse_args()

    rendered = render()

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None
        if current != rendered:
            print(
                "docs/changelog.md is out of date. "
                "Run: python scripts/generate_changelog_page.py"
            )
            return 1
        print("docs/changelog.md is up to date.")
        return 0

    TARGET.write_text(rendered, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
