#!/usr/bin/env python
"""One-shot migration of ``risk_types`` to the canonical vocabulary.

Plan 40 phase 3.3. Rewrites every bundled ``case.yaml`` in place:

* resolves each term through :data:`geocase.catalog.risk_types.RISK_TYPE_ALIASES`;
* drops ``"none"`` outright (9 cases) -- it is the absence of a risk type;
* moves ``format_comparison`` (60 cases) from ``risk_types`` to ``tags``, where
  it stays selectable as ``tags_any=["format_comparison"]``;
* adds ``transform/bottom_up`` and ``transform/pixel_anchor`` to the cases whose
  *declared assertions* already prove they carry those conventions.

That last step is not cosmetic. Both terms were in the canonical list with zero
cases, because the four cases carrying the two conventions that produced the
most severe findings of rounds 1 and 2 declared only ``nodata_ignored``. The
corpus's most productive axis was unsearchable by the index built to find it --
which is the drift this whole phase exists to stop.

Kept in the tree rather than deleted after running: it is the executable record
of what happened to each term, and ``CHANGELOG.md``'s corpus-changes entry
points at it.

Usage::

    python scripts/migrate_risk_types.py [--check]
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import yaml

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from geocase.catalog.risk_types import (  # noqa: E402
    RISK_TYPE_RETIRED,
    RISK_TYPES,
    canonical_risk_type,
)

DATA_ROOT = REPO_ROOT / "src" / "geocase" / "data" / "core"

#: Cases that carry a convention their ``risk_types`` never named.
#:
#: Derived from the declared assertions, not guessed: the two bottom-up cases
#: are the ones declaring ``positive_e`` in ``expected_transform_signs``, and
#: the two anchor cases are the ones declaring ``expected_pixel_anchor``.
BACKFILL: dict[str, list[str]] = {
    "bottom_up_dem_small": ["transform/bottom_up"],
    "rotated_bottom_up_small": ["transform/bottom_up"],
    "pixel_is_area_dem_small": ["transform/pixel_anchor"],
    "pixel_is_point_dem_small": ["transform/pixel_anchor"],
}


def migrate_one(raw: dict) -> tuple[list[str], list[str]]:
    """Return the new ``(risk_types, tags)`` for one case dict."""
    declared = list(raw.get("risk_types") or [])
    tags = list(raw.get("tags") or [])

    canonical: set[str] = set()
    for term in declared:
        if term in RISK_TYPE_RETIRED:
            # format_comparison survives as a tag; "none" survives as nothing.
            if term == "format_comparison" and term not in tags:
                tags.append(term)
            continue
        canonical.add(canonical_risk_type(term))

    canonical.update(BACKFILL.get(raw["id"], []))
    return sorted(canonical), tags


def _replace_block(text: str, key: str, values: list[str]) -> str:
    """Replace one top-level ``key:`` list block, leaving the rest byte-identical.

    A ``yaml.safe_dump`` round-trip would be far shorter and would destroy the
    thing that makes these files readable: the hand-authored ``>`` prose, the
    blank-line grouping, and the ``# Generated by ...`` banners that other
    ``--check`` gates match on. So this edits the block in place instead.
    """
    lines = text.split("\n")
    start = next(
        (
            i
            for i, line in enumerate(lines)
            if line.rstrip() in (f"{key}:", f"{key}: []")
        ),
        None,
    )
    if start is None:
        return text

    # Comments may sit *inside* a list block -- several GML/KML cases carry a
    # multi-line plan-34 note explaining why they declare axis_order -- so the
    # scan must step over an indented comment rather than stop at it, and the
    # comment has to survive into the rewritten block.
    end = start + 1
    comments: list[str] = []
    while end < len(lines):
        line = lines[end]
        stripped = line.strip()
        if line.startswith("  - "):
            end += 1
        elif stripped.startswith("#") and line.startswith(" "):
            comments.append(line)
            end += 1
        elif (
            stripped == ""
            and end + 1 < len(lines)
            and (
                lines[end + 1].startswith("  - ")
                or (
                    lines[end + 1].strip().startswith("#")
                    and lines[end + 1].startswith(" ")
                )
            )
        ):
            end += 1
        else:
            break

    # An explicit ``[]`` rather than a bare ``key:``, which YAML parses as
    # None. 48 baselines end up here, and that is the honest encoding: they
    # are canonical valid geometries with no failure mode, which is the only
    # job the literal string "none" was ever doing.
    if values:
        block = [f"{key}:"] + comments + [f"  - {v}" for v in values]
    else:
        block = [f"{key}: []"] + comments
    return "\n".join(lines[:start] + block + lines[end:])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report what would change and exit non-zero, without writing.",
    )
    args = parser.parse_args()

    changed: list[str] = []
    unknown: dict[str, list[str]] = {}

    for path in sorted(DATA_ROOT.rglob("*.yaml")):
        text = path.read_text()
        raw = yaml.safe_load(text)
        if not isinstance(raw, dict) or "risk_types" not in raw:
            continue

        new_risks, new_tags = migrate_one(raw)
        stray = [t for t in new_risks if t not in RISK_TYPES]
        if stray:
            unknown[raw["id"]] = stray

        if new_risks == list(raw.get("risk_types") or []) and new_tags == list(
            raw.get("tags") or []
        ):
            # Already canonical -- but a bare ``risk_types:`` still parses as
            # None and must become an explicit ``[]``.
            if not (new_risks == [] and "risk_types: []" not in text):
                continue

        changed.append(raw["id"])
        if args.check:
            continue

        updated = _replace_block(text, "risk_types", new_risks)
        if new_tags != list(raw.get("tags") or []):
            updated = _replace_block(updated, "tags", new_tags)
        path.write_text(updated)

        # Prove the edit round-trips to what was intended, rather than
        # trusting the text surgery.
        check = yaml.safe_load(path.read_text())
        assert list(check.get("risk_types") or []) == new_risks, raw["id"]
        assert list(check.get("tags") or []) == new_tags, raw["id"]

    if unknown:
        print(f"ERROR: terms outside the canonical vocabulary: {unknown}")
        return 1

    if args.check:
        if changed:
            print(f"{len(changed)} case(s) not migrated: {changed[:10]}")
            return 1
        print("All cases already carry canonical risk_types.")
        return 0

    print(f"Migrated {len(changed)} case(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
